### ISSUE TITLE
Support for screenshot testing

### ISSUE THREAD

**Issue by joaquimvila** [systelab/systelab-components-wdio-test#35]
**Is your feature request related to a problem? Please describe.**
It would be great to have utilities on this library to support testing based on screenshots. This is specially useful for checking some graphical elements such as plots/charts.

**Describe the solution you'd like**
Support methods to faciliate working with screenshots:
- Take a screenshot of the whole browser
- Take a screenshot of a DOM element
- Compare a taken screenshot with a provided golden copy

**Describe alternatives you've considered**
- Use of WDIO methods to take screenshots
- Use a 3rd party library for image comparison (i.e native-image-diff)

**Comment by jperez1-via** [comment]
Screenshot utility feature added and merged
