### ISSUE TITLE
Add support to find elements tagged using "systelabTestId" directive

### ISSUE THREAD

**Issue by joaquimvila** [systelab/systelab-components-wdio-test#37]
**Is your feature request related to a problem? Please describe.**
A new "systelabTestId" directive will be added on systelab-components library. It adds the "data-test-id" atributte to tagged HTML elements. These identifiers are intended for automated test purposes only, so it's clear from the development side these identifiers should be kept (or updated considering the test suites).

**Describe the solution you'd like**
Add methods at different levels of this library (ElementFinder, Browser, Page and Widget) to find an element (or all elements) that have the "data-test-id" HTML attribute. The goal of these new methods should be the centralization of this type of queries, so the projects don't need to know the name of this HTML attribute.

**Comment by joaquimvila** [comment]
Possible names for the new methods would be:

````typescript
public bySystelabTestId(id: string): ElementFinder
public allBySystelabTestId(id: string): ElementFinder
```

**Comment by amgart** [comment]
Hi! @joaquimvila! 
We discussed with @jserra91 , @fjaguado and @DaniMartinez-Gonzalez this new feature and we are working to make a proposal on this.
Just a comment, I would not use 'systelabTestId' and we should use a directive with a generic name. Something like 'dataTestId' or 'testId', as we are not systelab anymore. I think it is a good idea to not include a reference to the company name in the directive.
What do you think? :)

**Comment by Franek75** [comment]
Version 1.9 issued after the closure of this feature
